#!/bin/bash

BINCORE=/home/pi/HomeControl/bin/homecontrol
BINLOGGER=/home/pi/HomeControl/bin/logger
BINLOGVIEW=/home/pi/HomeControl/bin/logview
PATHWEBINTERFACE=/home/pi/HomeControl/WebInterface

function startCore {
	
	
	PS=`ps -A | grep homecontrol`

	if [ -n "$PS" ]; then
		echo 'HomeControl-Core is already running'
		#echo $PS
	else
		echo 'Starting core '
		stdbuf -oL $BINCORE daemon &> >($BINLOGGER)
			
		#PID='pgrep -n -x homecontrol'
		#echo "$PID"
		#sleep 1
	fi
}

function stopCore {
	echo 'Stopping core '
	killall -INT homecontrol
}

function startWeb {
	PS=`ps -A | grep node`

	if [ -n "$PS" ]; then
		echo 'HomeControl-WebServer is already running'
		#echo $PS
	else
		echo 'Starting webserver '
		cd $PATHWEBINTERFACE
		nohup sudo node index.js > /dev/null 2>&1 &
	fi
}

function stopWeb {
	echo 'Stopping webserver '
	sudo killall -INT node
}

function log {
	#echo 'Showing log '
	$BINLOGVIEW
}

function startAll {
	startCore
	startWeb
}

function stopAll {
	stopCore
	stopWeb
}

case "$1" in
  startcore)
	startCore
	;;
  stopcore)
	stopCore
	;;
  startweb)
  startWeb
	;;
  stopweb)
  stopWeb
	;;
  log)
  log
	;;
  startall)
  startAll
	;;
  stopall)
  stopAll
	;;
  *)
	echo $"Usage: $0 {startcore|stopcore|startweb|stopweb|log|startall|stopall}"
	exit 1
esac

exit 0
